# Generated by Django 5.0.6 on 2024-06-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_remove_collection_total_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='entries',
        ),
        migrations.AddField(
            model_name='entry',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
    ]
