# Generated by Django 5.0.6 on 2024-06-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_collection_entries_entry_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
    ]
