# Generated by Django 5.0.6 on 2024-06-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_cards', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card_type', models.CharField(choices=[('regular', 'Regular'), ('holo', 'Holo'), ('reverse_holo', 'Reverse Holo')], default='regular', max_length=50)),
                ('number', models.IntegerField()),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('double_rare', 'Double Rare'), ('ultra_rare', 'Ultra Rare'), ('illustration_rare', 'Illustration Rare'), ('special_illustration_rare', 'Special Illustration Rare'), ('hyper_rare', 'Hyper Rare')], default='common', max_length=50)),
                ('generation', models.PositiveSmallIntegerField()),
                ('pokedex_number', models.IntegerField()),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.expansion')),
            ],
        ),
        migrations.AddField(
            model_name='expansion',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.series'),
        ),
    ]
