# Generated by Django 5.0.6 on 2024-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
        migrations.AddField(
            model_name='card',
            name='reverse_holo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('regular', 'Regular'), ('illustration_rare', 'Illustration Rare'), ('special_illustration_rare', 'Special Illustration Rare'), ('hyper_rare', 'Hyper Rare')], default='regular', max_length=50),
        ),
    ]
