# Generated by Django 5.0.6 on 2024-06-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_remove_card_card_type_card_reverse_holo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expansion',
            new_name='Set',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='expansion',
            new_name='set',
        ),
    ]
